print("bilgisayar","bilimi")
print("bilgisayar" + " " + "bilimi")
print("bilgisayar bilimi")
print("bilgisayar" " " "Bilimi")
print('5')
print(5)
print(5+4)
print("5"+"4")
print(type("a"))
print(type(2.5))
print(type(3))
str(5)
int("5")
float(4)
print(len("türkiye"))
print(2+2)
print(2-2)
print(2*2)
print(2/2)
print(2**2)
print(2//2)
print("2"*2) #yorum satırı gaming